### ISSUE TITLE
Support listing blueprint tiles

### ISSUE THREAD

**Issue by veksen** [factorio-builds/factorio-builds-tech#465]

**Comment by veksen** [comment]
@dstockhammer I need the entities to be part of the payload for this

**Comment by dstockhammer** [comment]
I don't quite understand this feature; can you please elaborate or show me a mockup?

**Comment by veksen** [comment]
I want to list the tiles here, but they are not part of the payload:

![image](https://user-images.githubusercontent.com/3461986/110349153-6a7f1200-8000-11eb-8181-4fa3f471f412.png)

**Comment by dstockhammer** [comment]
fixed in #482
